load property

(omod WALTER-ANALYSIS is
  inc PROPERTY .

  eq f = 1 .  --- no failure

  ops r1 r2 r3 r4 t1 t2 t3 t4 t5 t6 tb m : -> Oid [ctor] .
  ops x y : -> Key [ctor] .
  ops xl yl : -> LocalVar [ctor] .

  --- initial states:
  ops init1 init2 init3 init4 init5 init6 init7 init8 init9 : -> Configuration .

  --- one read and one write; one key; one replica; one txn
  eq init1 =
     < m : Monitor | clock : 0, log : empty > 
     < tb : Table | table : [replicatingSites(x, r1)] >
     < r1 : Replica | gotTxns : (< t1 : Txn | operations : ((xl :=read x) write(x,1)), readSet : empty, 
                                              writeSet : empty, localVars : (xl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 >),
                      history : (x |-> (< [0],version(0,0) >)), sqn : 0, 
                      executing : emptyTxnList, committed : emptyTxnList, aborted : emptyTxnList, 
                      committedVTS : empty, gotVTS : empty, locked : empty, dsSites : noPS, vsbSites : noVS,
                      dsTxns : empty, gvTxns : empty, recPropTxns : noPT, recDurableTxns : noDT, 
                      votes : noVote, voteSites : noVS, abortSites : noVS > .
		
  --- one read and one write; one key; two replicas; one txn
  eq init2 = 
     < m : Monitor | clock : 0, log : empty > 
     < tb : Table | table : [replicatingSites(x, r1 r2)] >
     < r1 : Replica | gotTxns : (< t1 : Txn | operations : ((xl :=read x) write(x,1)), readSet : empty, 
                                              writeSet : empty, localVars : (xl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 >),
                      history : (x |-> (< [0],version(0,0) >)), sqn : 0, 
                      executing : emptyTxnList, committed : emptyTxnList, aborted : emptyTxnList, 
                      committedVTS : empty, gotVTS : empty, locked : empty, dsSites : noPS, vsbSites : noVS,
                      dsTxns : empty, gvTxns : empty, recPropTxns : noPT, recDurableTxns : noDT, 
                      votes : noVote, voteSites : noVS, abortSites : noVS >
     < r2 : Replica | gotTxns : emptyTxnList,
                      history : (x |-> (< [0],version(0,0) >)), sqn : 0, 
                      executing : emptyTxnList, committed : emptyTxnList, aborted : emptyTxnList, 
                      committedVTS : empty, gotVTS : empty, locked : empty, dsSites : noPS, vsbSites : noVS,
                      dsTxns : empty, gvTxns : empty, recPropTxns : noPT, recDurableTxns : noDT, 
                      votes : noVote, voteSites : noVS, abortSites : noVS > .

  --- one read and one write; two keys; two replicas; two txns
  eq init3 = 
     < m : Monitor | clock : 0, log : empty > 
     < tb : Table | table : [replicatingSites(x, r1 r2) ;; replicatingSites(y, r1 r2)] >
     < r1 : Replica | gotTxns : (< t1 : Txn | operations : ((xl :=read x) write(x,1)), readSet : empty, 
                                              writeSet : empty, localVars : (xl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 >),
                      history : (x |-> (< [0],version(0,0) >), y |-> (< [0],version(0,0) >)), sqn : 0, 
                      executing : emptyTxnList, committed : emptyTxnList, aborted : emptyTxnList, 
                      committedVTS : empty, gotVTS : empty, locked : empty, dsSites : noPS, vsbSites : noVS,
                      dsTxns : empty, gvTxns : empty, recPropTxns : noPT, recDurableTxns : noDT, 
                      votes : noVote, voteSites : noVS, abortSites : noVS >
     < r2 : Replica | gotTxns : (< t2 : Txn | operations : ((yl :=read y) write(y,1)), readSet : empty, 
                                              writeSet : empty, localVars : (yl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 >),
                      history : (x |-> (< [0],version(0,0) >), y |-> (< [0],version(0,0) >)), sqn : 0, 
                      executing : emptyTxnList, committed : emptyTxnList, aborted : emptyTxnList, 
                      committedVTS : empty, gotVTS : empty, locked : empty, dsSites : noPS, vsbSites : noVS,
                      dsTxns : empty, gvTxns : empty, recPropTxns : noPT, recDurableTxns : noDT, 
                      votes : noVote, voteSites : noVS, abortSites : noVS > .

  ---
  eq init4 = 
     < tb : Table | table : [replicatingSites(x, r1 r2) ;; replicatingSites(y, r2 r1)] >
     < r1 : Replica | gotTxns : (< t1 : Txn | operations : ((xl :=read x) write(x,1)), readSet : empty, 
                                              writeSet : empty, localVars : (xl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 > ;;
                                 < t3 : Txn | operations : ((yl :=read y) write(y,2)), readSet : empty, 
                                              writeSet : empty, localVars : (yl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 >
                                ),
                      history : (x |-> (< [0],version(0,0) >), y |-> (< [0],version(0,0) >)), sqn : 0, 
                      executing : emptyTxnList, committed : emptyTxnList, aborted : emptyTxnList, 
                      committedVTS : empty, gotVTS : empty, locked : empty, dsSites : noPS, vsbSites : noVS,
                      dsTxns : empty, gvTxns : empty, recPropTxns : noPT, recDurableTxns : noDT, 
                      votes : noVote, voteSites : noVS, abortSites : noVS >
     < r2 : Replica | gotTxns : (< t2 : Txn | operations : ((yl :=read y) write(y,1)), readSet : empty, 
                                              writeSet : empty, localVars : (yl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 > ;;
                                 < t4 : Txn | operations : ((xl :=read x) write(x,2)), readSet : empty, 
                                              writeSet : empty, localVars : (xl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 >
                                ),
                      history : (x |-> (< [0],version(0,0) >), y |-> (< [0],version(0,0) >)), sqn : 0, 
                      executing : emptyTxnList, committed : emptyTxnList, aborted : emptyTxnList, 
                      committedVTS : empty, gotVTS : empty, locked : empty, dsSites : noPS, vsbSites : noVS,
                      dsTxns : empty, gvTxns : empty, recPropTxns : noPT, recDurableTxns : noDT, 
                      votes : noVote, voteSites : noVS, abortSites : noVS > .


  eq init5 = 
     < tb : Table | table : [replicatingSites(x, r1 r2 r3) ;; replicatingSites(y, r2 r1 r3)] >
     < r1 : Replica | gotTxns : (< t1 : Txn | operations : ((xl :=read x) write(x,1)), readSet : empty, 
                                              writeSet : empty, localVars : (xl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 > ;;
                                 < t3 : Txn | operations : ((yl :=read y) write(y,2)), readSet : empty, 
                                              writeSet : empty, localVars : (yl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 >
                                ),
                      history : (x |-> (< [0],version(0,0) >), y |-> (< [0],version(0,0) >)), sqn : 0, 
                      executing : emptyTxnList, committed : emptyTxnList, aborted : emptyTxnList, 
                      committedVTS : empty, gotVTS : empty, locked : empty, dsSites : noPS, vsbSites : noVS,
                      dsTxns : empty, gvTxns : empty, recPropTxns : noPT, recDurableTxns : noDT, 
                      votes : noVote, voteSites : noVS, abortSites : noVS >
     < r2 : Replica | gotTxns : (< t2 : Txn | operations : ((yl :=read y) write(y,1)), readSet : empty, 
                                              writeSet : empty, localVars : (yl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 > ;;
                                 < t4 : Txn | operations : ((xl :=read x) write(x,2)), readSet : empty, 
                                              writeSet : empty, localVars : (xl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 >
                                ),
                      history : (x |-> (< [0],version(0,0) >), y |-> (< [0],version(0,0) >)), sqn : 0, 
                      executing : emptyTxnList, committed : emptyTxnList, aborted : emptyTxnList, 
                      committedVTS : empty, gotVTS : empty, locked : empty, dsSites : noPS, vsbSites : noVS,
                      dsTxns : empty, gvTxns : empty, recPropTxns : noPT, recDurableTxns : noDT, 
                      votes : noVote, voteSites : noVS, abortSites : noVS >
     < r3 : Replica | gotTxns : emptyTxnList,
                      history : (x |-> (< [0],version(0,0) >), y |-> (< [0],version(0,0) >)), sqn : 0, 
                      executing : emptyTxnList, committed : emptyTxnList, aborted : emptyTxnList, 
                      committedVTS : empty, gotVTS : empty, locked : empty, dsSites : noPS, vsbSites : noVS,
                      dsTxns : empty, gvTxns : empty, recPropTxns : noPT, recDurableTxns : noDT, 
                      votes : noVote, voteSites : noVS, abortSites : noVS > .

  eq init6 = 
     < tb : Table | table : [replicatingSites(x, r2 r1) ;; replicatingSites(y, r2 r1)] >
     < r1 : Replica | gotTxns : (< t1 : Txn | operations : ((xl :=read x) write(x,1)), readSet : empty, 
                                              writeSet : empty, localVars : (xl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 > ;;
                                 < t3 : Txn | operations : ((yl :=read y) write(y,2)), readSet : empty, 
                                              writeSet : empty, localVars : (yl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 > ;;
                                 < t2 : Txn | operations : ((yl :=read y) write(y,1)), readSet : empty, 
                                              writeSet : empty, localVars : (yl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 > ;;
                                 < t4 : Txn | operations : ((xl :=read x) write(x,2)), readSet : empty, 
                                              writeSet : empty, localVars : (xl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 >
                                ),
                      history : (x |-> (< [0],version(0,0) >), y |-> (< [0],version(0,0) >)), sqn : 0, 
                      executing : emptyTxnList, committed : emptyTxnList, aborted : emptyTxnList, 
                      committedVTS : empty, gotVTS : empty, locked : empty, dsSites : noPS, vsbSites : noVS,
                      dsTxns : empty, gvTxns : empty, recPropTxns : noPT, recDurableTxns : noDT, 
                      votes : noVote, voteSites : noVS, abortSites : noVS >
     < r2 : Replica | gotTxns : emptyTxnList,
                      history : (x |-> (< [0],version(0,0) >), y |-> (< [0],version(0,0) >)), sqn : 0, 
                      executing : emptyTxnList, committed : emptyTxnList, aborted : emptyTxnList, 
                      committedVTS : empty, gotVTS : empty, locked : empty, dsSites : noPS, vsbSites : noVS,
                      dsTxns : empty, gvTxns : empty, recPropTxns : noPT, recDurableTxns : noDT, 
                      votes : noVote, voteSites : noVS, abortSites : noVS >
     < r3 : Replica | gotTxns : emptyTxnList,
                      history : (x |-> (< [0],version(0,0) >), y |-> (< [0],version(0,0) >)), sqn : 0, 
                      executing : emptyTxnList, committed : emptyTxnList, aborted : emptyTxnList, 
                      committedVTS : empty, gotVTS : empty, locked : empty, dsSites : noPS, vsbSites : noVS,
                      dsTxns : empty, gvTxns : empty, recPropTxns : noPT, recDurableTxns : noDT, 
                      votes : noVote, voteSites : noVS, abortSites : noVS > .

  --- 
  eq init7 = 
     < m : Monitor | clock : 0, log : empty > 
     < tb : Table | table : [replicatingSites(x, r1 r2) ;; replicatingSites(y, r2 r1)] >
     < r1 : Replica | gotTxns : (< t1 : Txn | operations : ((xl :=read x) write(x,1)), readSet : empty, 
                                              writeSet : empty, localVars : (xl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 > ;;
                                 < t3 : Txn | operations : ((xl :=read x) (yl :=read y)), readSet : empty, 
                                              writeSet : empty, localVars : (xl |-> [0], yl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 >
                                ),
                      history : (x |-> (< [0],version(0,0) >), y |-> (< [0],version(0,0) >)), sqn : 0, 
                      executing : emptyTxnList, committed : emptyTxnList, aborted : emptyTxnList, 
                      committedVTS : empty, gotVTS : empty, locked : empty, dsSites : noPS, vsbSites : noVS,
                      dsTxns : empty, gvTxns : empty, recPropTxns : noPT, recDurableTxns : noDT, 
                      votes : noVote, voteSites : noVS, abortSites : noVS >
     < r2 : Replica | gotTxns : (< t2 : Txn | operations : ((yl :=read y) write(y,2)), readSet : empty, 
                                              writeSet : empty, localVars : (yl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 > ;;
                                 < t4 : Txn | operations : ((xl :=read x) (yl :=read y)), readSet : empty, 
                                              writeSet : empty, localVars : (xl |-> [0], yl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 >
                                ),
                      history : (x |-> (< [0],version(0,0) >), y |-> (< [0],version(0,0) >)), sqn : 0, 
                      executing : emptyTxnList, committed : emptyTxnList, aborted : emptyTxnList, 
                      committedVTS : empty, gotVTS : empty, locked : empty, dsSites : noPS, vsbSites : noVS,
                      dsTxns : empty, gvTxns : empty, recPropTxns : noPT, recDurableTxns : noDT, 
                      votes : noVote, voteSites : noVS, abortSites : noVS > .
  
  eq init8 = 
     < m : Monitor | clock : 0, log : empty > 
     < tb : Table | table : [replicatingSites(x, r1 r2) ;; replicatingSites(y, r2 r1)] >
     < r1 : Replica | gotTxns : (< t1 : Txn | operations : ((xl :=read x) write(x,1)), readSet : empty, 
                                              writeSet : empty, localVars : (xl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 > ;;
                                 < t3 : Txn | operations : ((xl :=read x) (yl :=read y)), readSet : empty, 
                                              writeSet : empty, localVars : (xl |-> [0], yl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 >
                                ),
                      history : (x |-> (< [0],version(0,0) >), y |-> (< [0],version(0,0) >)), sqn : 0, 
                      executing : emptyTxnList, committed : emptyTxnList, aborted : emptyTxnList, 
                      committedVTS : empty, gotVTS : empty, locked : empty, dsSites : noPS, vsbSites : noVS,
                      dsTxns : empty, gvTxns : empty, recPropTxns : noPT, recDurableTxns : noDT, 
                      votes : noVote, voteSites : noVS, abortSites : noVS >
     < r2 : Replica | gotTxns : (< t2 : Txn | operations : ((yl :=read y) write(y,2)), readSet : empty, 
                                              writeSet : empty, localVars : (yl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 >
                                ),
                      history : (x |-> (< [0],version(0,0) >), y |-> (< [0],version(0,0) >)), sqn : 0, 
                      executing : emptyTxnList, committed : emptyTxnList, aborted : emptyTxnList, 
                      committedVTS : empty, gotVTS : empty, locked : empty, dsSites : noPS, vsbSites : noVS,
                      dsTxns : empty, gvTxns : empty, recPropTxns : noPT, recDurableTxns : noDT, 
                      votes : noVote, voteSites : noVS, abortSites : noVS > .

  eq init9 = 
     < m : Monitor | clock : 0, log : empty > 
     < tb : Table | table : [replicatingSites(x, r1 r2) ;; replicatingSites(y, r1 r2)] >
     < r1 : Replica | gotTxns : (< t1 : Txn | operations : ((xl :=read x) write(x,1)), readSet : empty, 
                                              writeSet : empty, localVars : (xl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 > ;;
                                 < t3 : Txn | operations : ((xl :=read x) (yl :=read y)), readSet : empty, 
                                              writeSet : empty, localVars : (xl |-> [0], yl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 >
                                ),
                      history : (x |-> (< [0],version(0,0) >), y |-> (< [0],version(0,0) >)), sqn : 0, 
                      executing : emptyTxnList, committed : emptyTxnList, aborted : emptyTxnList, 
                      committedVTS : empty, gotVTS : empty, locked : empty, dsSites : noPS, vsbSites : noVS,
                      dsTxns : empty, gvTxns : empty, recPropTxns : noPT, recDurableTxns : noDT, 
                      votes : noVote, voteSites : noVS, abortSites : noVS >
     < r2 : Replica | gotTxns : (< t2 : Txn | operations : ((xl :=read x) write(x,2)), readSet : empty, 
                                              writeSet : empty, localVars : (xl |-> [0]), 
                                              startVTS : empty, txnSQN : 0 > 
                                ),
                      history : (x |-> (< [0],version(0,0) >), y |-> (< [0],version(0,0) >)), sqn : 0, 
                      executing : emptyTxnList, committed : emptyTxnList, aborted : emptyTxnList, 
                      committedVTS : empty, gotVTS : empty, locked : empty, dsSites : noPS, vsbSites : noVS,
                      dsTxns : empty, gvTxns : empty, recPropTxns : noPT, recDurableTxns : noDT, 
                      votes : noVote, voteSites : noVS, abortSites : noVS > .

endom)

---(rew init1 .)
--- t1 committed

---(rew init2 .)
--- t1 committed

---(rew init3 .)
--- t1, t2 committed

---(rew init4 .)
---(rew init7 .)
---(rew init9 .)

---(search init3 =>! C:Configuration .)
---(search init4 =>! C:Configuration .)
---(search init5 =>! C:Configuration .)
---(search init6 =>! C:Configuration .)
---(search init9 =>! C:Configuration .)

---(search [1] init7 =>! < M:Oid : Monitor | log : LOG:Log > C:Configuration such that not p1-si(LOG:Log) .)
---(search [1] init7 =>! < M:Oid : Monitor | log : LOG:Log > C:Configuration such that not p1-psi(LOG:Log) .)

---(search [1] init9 =>! < M:Oid : Monitor | log : LOG:Log > C:Configuration such that not p1-psi(LOG:Log) .)

---(search [1] init7 =>! < M:Oid : Monitor | log : LOG:Log > C:Configuration such that p2-si(LOG:Log) .)
---(search [1] init7 =>! < M:Oid : Monitor | log : LOG:Log > C:Configuration such that p2-psi(LOG:Log) .)
---(search [1] init7 =>! < M:Oid : Monitor | log : LOG:Log > C:Configuration such that p3-psi(LOG:Log) .)

---(search [1] init8 =>! < M:Oid : Monitor | log : LOG:Log > C:Configuration such that p3-psi(LOG:Log) .)

---(search init(0,0,2,2,2,rf) =>! C:Configuration .)
---(search init(1,2,0,2,2,rf) =>! C:Configuration .)

(search [1] init(0,0,3,2,2,rf) =>! < M:Oid : Monitor | log : LOG:Log > C:Configuration such that not p1-psi(LOG:Log) .)

q
