load initial-states-mc
load model-checker

mod ROLA-ANALYSIS is
  including INITIAL-STATES .
  including APMAUDE .
  including MODEL-CHECKER .

  subsort Config < State .

  eq LIMIT = 10000000.0 .

  op initConfig : -> Config .
  ---eq initConfig = run(initState,LIMIT) .

  ops x y z : -> Key .
  ops tb r1 r2 r3 t1 t2 t3 t4 : -> Address .
  ops xl yl zl : -> LocalVar .
  
  --- init(RTX,WTX,RWTX,REPLS,KEYS,ROPS,WOPS,RWOPS,KAD) 
  ---eq initState = init(1,0,1,2,2,2,2,4,zipf) .


  eq initConfig = < tb : Table | table: [replicatingSites(x, 1) ;; replicatingSites(y, 2)] > 
     (start to 1) (start to 2)
     < 0 : Monitor | clock: 0, log: empty >     

     < 1 : Replica | gotTxns:  (< t3 : Txn | operations: ((xl :=read x) write(x,2) (yl :=read y) write(y,3)), readSet: empty, 
                                             latest: empty, localVars: (xl |-> [0], yl |-> [0]), txnSQN: 0,
                                             writeSet: empty, version: eptVersion > ), 
                      datastore: (version(x,[0],eptTS,empty)), sqn: 1, latestCommit: empty, 
                      executing: noActor, 
                      committed: emptyTxnList, aborted: emptyTxnList, votes: noVote,
                      voteSites: noVS, 
                       1stGetSites: no1st,
                       2ndGetSites: no2nd, commitSites: noVS, tsSqn: empty > 

     < 2 : Replica | gotTxns: (< t1 : Txn | operations: ((xl :=read x) write(x,1) (yl :=read y) write(y,1)), readSet: empty, 
                                             latest: empty, localVars: (xl |-> [0], yl |-> [0]), txnSQN: 0,
                                             writeSet: empty, version: eptVersion > ), 
                      datastore: (version(y,[0],eptTS,empty)), sqn: 1, latestCommit: empty, 
                      executing: noActor, 
                      committed: emptyTxnList, aborted: emptyTxnList, votes: noVote,
                      voteSites: noVS, 
                       1stGetSites: no1st,
                       2ndGetSites: no2nd, commitSites: noVS, tsSqn: empty > .
  
endm

---set clear rules off .
---rewrite initConfig .
search initConfig =>! C:Config .
---rewrite totalRunTime?(initConfig) .


