load consistency
load model-checker

mod ROLA-ANALYSIS is
  inc INITIAL-STATES .
  inc CONSISTENCY .
  inc MODEL-CHECKER .

  --- Init parameters 
  eq nbOfRoTxns = 0 .  eq nbOfOpsPerRoTxn = 0 .
  eq nbOfWoTxns = 0 .  eq nbOfOpsPerWoTxn = 0 .
  eq nbOfRwTxns = 3 .  eq nbOfOpsPerRwTxn = 4 .  --- must be even number
  eq nbOfServs  = 2 .  eq nbOfKeys = 2 .  eq nbOfRepls = 1 .


  op initConfig : -> Config .
  eq initConfig = init(nbOfRoTxns,nbOfWoTxns,nbOfRwTxns,
      nbOfOpsPerRoTxn,nbOfOpsPerWoTxn,nbOfOpsPerRwTxn, 
      nbOfServs,nbOfKeys,nbOfRepls) . 

  ---(
  ops x y z : -> Key .
  ops tb r1 r2 r3 t1 t2 t3 t4 : -> Address .
  ops xl yl zl : -> LocalVar .

  eq initConfig = < tb : Table | table: [replicatingSites(x, 1) ;; replicatingSites(y, 2)] > 
     (start to 1) (start to 2)
     < 0 : Monitor | clock: 0, log: empty >     

     < 1 : Replica | gotTxns:  (< t3 : Txn | operations: ((xl :=read x) write(x,2) (yl :=read y) write(y,3)), readSet: empty, 
                                             latest: empty, localVars: (xl |-> [0], yl |-> [0]), txnSQN: 0,
                                             writeSet: empty, version: eptVersion > ), 
                      datastore: (version(x,[0],eptTS,empty)), sqn: 1, latestCommit: empty, 
                      executing: noActor, 
                      committed: emptyTxnList, aborted: emptyTxnList, votes: noVote,
                      voteSites: noVS, 
                       1stGetSites: no1st,
                       2ndGetSites: no2nd, commitSites: noVS, tsSqn: empty > 

     < 2 : Replica | gotTxns: (< t1 : Txn | operations: ((xl :=read x) write(x,1) (yl :=read y) write(y,1)), readSet: empty, 
                                             latest: empty, localVars: (xl |-> [0], yl |-> [0]), txnSQN: 0,
                                             writeSet: empty, version: eptVersion > ), 
                      datastore: (version(y,[0],eptTS,empty)), sqn: 1, latestCommit: empty, 
                      executing: noActor, 
                      committed: emptyTxnList, aborted: emptyTxnList, votes: noVote,
                      voteSites: noVS, 
                       1stGetSites: no1st,
                       2ndGetSites: no2nd, commitSites: noVS, tsSqn: empty > .
  )


endm

---rew initConfig .
---search initConfig =>! C:Config .

---search [1] initConfig =>! < M:Address : Monitor | log: LOG:Log, AS:AttributeSet > C:Config 
  ---such that not rc(LOG:Log) .

---search [1] initConfig =>! < M:Address : Monitor | log: LOG:Log, AS:AttributeSet > C:Config 
  ---such that not ra(LOG:Log) .

---search [1] initConfig =>! < M:Address : Monitor | log: LOG:Log, AS:AttributeSet > C:Config 
  ---such that not cs(LOG:Log) .

---search [1] initConfig =>! < M:Address : Monitor | log: LOG:Log, AS:AttributeSet > C:Config 
  ---such that not ua(LOG:Log) .

---search [1] initConfig =>! < M:Address : Monitor | log: LOG:Log, AS:AttributeSet > C:Config 
  ---such that not si(LOG:Log) .

search [1] initConfig =>! < M:Address : Monitor | log: LOG:Log, AS:AttributeSet > C:Config 
  such that not psi(LOG:Log) .

---search [1] initConfig =>! < M:Address : Monitor | log: LOG:Log, AS:AttributeSet > C:Config 
  ---such that not nmsi(LOG:Log) .
q

