tagRules(crl '<_:_|_>['A:Address,'Client.ActorType,'_`,_['requestQueue:_['_;;_['<_:_|_>[
    'TID:Address,'Txn.ActorType,'_`,_['operations:_['OP:Operation],'AS':AttributeSet]],
    'TRANSES:ConfigList]],'_`,_['waitingList:_['TRANSES':ConfigList],'_`,_['lockedKeys:_[
    'LOCKS:Set`{LockedKey`}],'_`,_['executing:_['TXNS:Config],'AS:AttributeSet]]]]] =>
    '<_:_|_>['A:Address,'Client.ActorType,'_`,_['requestQueue:_['TRANSES:ConfigList],'_`,_[
    'waitingList:_['_;;_['TRANSES':ConfigList,'<_:_|_>['TID:Address,'Txn.ActorType,'_`,_[
    'operations:_['OP:Operation],'AS':AttributeSet]]]],'_`,_['lockedKeys:_[
    'LOCKS:Set`{LockedKey`}],'_`,_['executing:_['TXNS:Config],'AS:AttributeSet]]]]] if
    'isLocked['OP:Operation,'LOCKS:Set`{LockedKey`}] = 'true.Bool [label('dequeue-1)] .)

    