load initial-states-smc

mod WALTER-ANALYSIS is
  including INITIAL-STATES .
  including APMAUDE .
  including MODEL-CHECKER .

  subsort Config < State .

  eq LIMIT = 10000000.0 .

  op initConfig : -> Config .
  eq initConfig = run(initState,LIMIT) .

  ops x y z : -> Key .
  ops tb r1 r2 r3 t1 t2 t3 t4 t5 t6 : -> Address .
  ops xl yl zl : -> LocalVar .
  
  --- init(RTX,WTX,RWTX,REPLS,KEYS,ROPS,WOPS,RWOPS,KAD) 
  ---eq initState = init(0,0,2,2,2,2,2,2,uniform) .

  ---
  eq initState = { 0.0 | nil} < tb : Table | table: [replicatingSites(x, 1) ;; replicatingSites(y, 2)] > 
                 { 0.0, start to 1} { 0.0, start to 2}
                 < 0 : Monitor | log: empty > 
     < 1 : Replica | gotTxns: ( < t1 : Txn | operations: ((xl :=read x) write(x,1) (yl :=read y) write(y,1)), readSet: empty, 
                                             writeSet: empty, localVars: (xl |-> [0], yl |-> [0]), 
                                             startVTS: empty, txnSQN: 0, version: eptVersion >),
                     history: (x |-> (< [0],< 0,0 > >)), sqn: 0, 
                      executing: noActor, 
                      committed: emptyTxnList, aborted: emptyTxnList, 
                      committedVTS: empty, gotVTS: empty,
                      locked: empty, dsSites: noPS, vsbSites: noVS,
                      dsTxns: emptyAddressSet, gvTxns: emptyAddressSet, recPropTxns: noPT,
                      recDurableTxns: noDT, votes: noVote,
                      voteSites: noVS, abortSites: noVS,
                      rmtCommitted: emptyAddressSet > 
   
     < 2 : Replica | gotTxns: (
                               < t2 : Txn | operations: ((xl :=read x) write(x,5) (yl :=read y) write(y,6)), readSet: empty, 
                                             writeSet: empty, localVars: (xl |-> [0], yl |-> [0]), 
                                             startVTS: empty, txnSQN: 0, version: eptVersion >), 
                     history: (y |-> (< [0],< 0,0 > >)), sqn: 0, 
                      executing: noActor, 
                      committed: emptyTxnList, aborted: emptyTxnList, 
                      committedVTS: empty, gotVTS: empty,
                      locked: empty, dsSites: noPS, vsbSites: noVS,
                      dsTxns: emptyAddressSet, gvTxns: emptyAddressSet, recPropTxns: noPT,
                      recDurableTxns: noDT, votes: noVote,
                      voteSites: noVS, abortSites: noVS,
                      rmtCommitted: emptyAddressSet > .
  

---(
  --- Metrics
  vars T T' T1 T2 NUMBER : Float .
  var C : Config .
  vars M TID : Address .
  vars RECORD RECORD' : Record . 
  var FLAG : Bool .

  --- Throughput
  op totalRunTime : Record -> Float .
  op trt : Record Float -> Float .
  eq totalRunTime(RECORD) = trt(RECORD,0.0) .
  eq trt((record(TID,T1,T2,FLAG) ; RECORD),T) = 
       if T2 > T
         then trt(RECORD,T2)
         else trt(RECORD,T)
       fi .
  eq trt(noRecord,T) = T .
         
  op throughput : Config -> Float .
  eq throughput(< M : Monitor | log: RECORD > C) = committedNumber(RECORD) / totalRunTime(RECORD) .

  op committedNumber : Record -> Float .
  op $committedNumber : Record Float -> Float .
  eq committedNumber(RECORD) = $committedNumber(RECORD,0.0) .
  eq $committedNumber((record(TID,T1,T2,true) ; RECORD),NUMBER) = 
       $committedNumber(RECORD,NUMBER + 1.0) .
  eq $committedNumber((record(TID,T1,T2,false) ; RECORD),NUMBER) = 
       $committedNumber(RECORD,NUMBER) .
  eq $committedNumber(noRecord,NUMBER) = NUMBER .

  --- Commit Rate
  op commitRate : Config -> Float .
  eq commitRate(< M : Monitor | log: RECORD > C) = committedNumber(RECORD) / totalNumber(RECORD) .

  op totalNumber : Record -> Float .
  op $totalNumber : Record Float -> Float .
  eq totalNumber(RECORD) = $totalNumber(RECORD,0.0) .
  eq $totalNumber((record(TID,T1,T2,FLAG) ; RECORD),NUMBER) = 
       $totalNumber(RECORD,NUMBER + 1.0) .
  eq $totalNumber(noRecord,NUMBER) = NUMBER .  

  --- Avg Latency
  op avgLatency : Config -> Float .
  eq avgLatency(< M : Monitor | log: RECORD > C) = totalLatency(RECORD) / committedNumber(RECORD) .
  
  op totalLatency : Record -> Float .
  op $totalLatency : Record Float -> Float .
  eq totalLatency(RECORD) = $totalLatency(RECORD,0.0) .
  eq $totalLatency((record(TID,T1,T2,true) ; RECORD),NUMBER) =
       $totalLatency(RECORD,NUMBER + T2 - T1) .
  eq $totalLatency((record(TID,T1,T2,false) ; RECORD),NUMBER) = 
       $totalLatency(RECORD,NUMBER) .
  eq $totalLatency(noRecord,NUMBER) = NUMBER .

  --- PVESTA interfaces
  eq val(0,C) = throughput(C) .
  eq val(1,C) = avgLatency(C) .
  eq val(2,C) = commitRate(C) .
)
endm

set clear rules off .
---rewrite commitRate(initConfig) .
---rewrite (not modified((x |-> [1]),empty,(x |-> < [0],version(0, 0) >))) .
---rewrite (not locked((x |-> [1]),empty)) .
---rewrite update((x |-> [1]),version(1,2),(x |-> < [0],version(0, 0) >)) .
---rew initConfig .
---(
rew run(
{0.0 |
[toplevel,[2.4876941713491956,execute to 1]] ;
[toplevel,[3.6440476531518917,execute to 2]]} 
< 0 : Monitor | log: (t1 |-> < 1 |-> 0.0,empty,false,empty,empty >, t2 |-> < 2
    |-> 0.0,empty,false,empty,empty >) > 
< tb : Table | table: [replicatingSites(x, 1) ;; replicatingSites(y, 2)] > 
< 1 : Replica | history: (x |-> < [0],< 0,0 > >),sqn: 0,executing: 
< t1 : Txn | operations: ((xl :=read x) write(x, 1) (yl :=read y) write(y, 1)),
    readSet: empty,writeSet: empty,localVars: (xl |-> [0], yl |-> [0]),
    startVTS: empty,txnSQN: 0,version: eptVersion >,committed: emptyTxnList,
    aborted: emptyTxnList,committedVTS: empty,gotVTS: empty,locked: empty,
    gotTxns: emptyTxnList,dsSites: noPS,vsbSites: noVS,dsTxns: emptyAddressSet,
    gvTxns: emptyAddressSet,recPropTxns: noPT,recDurableTxns: noDT,votes:
    noVote,voteSites: noVS,abortSites: noVS,rmtCommitted: emptyAddressSet > 
< 2 : Replica | history: (y |-> < [0],< 0,0 > >),sqn: 0,executing: 
< t2 : Txn | operations: ((xl :=read x) write(x, 5) (yl :=read y) write(y, 6)),
    readSet: empty,writeSet: empty,localVars: (xl |-> [0], yl |-> [0]),
    startVTS: empty,txnSQN: 0,version: eptVersion >,committed: emptyTxnList,
    aborted: emptyTxnList,committedVTS: empty,gotVTS: empty,locked: empty,
    gotTxns: emptyTxnList,dsSites: noPS,vsbSites: noVS,dsTxns: emptyAddressSet,
    gvTxns: emptyAddressSet,recPropTxns: noPT,recDurableTxns: noDT,votes:
    noVote,voteSites: noVS,abortSites: noVS,rmtCommitted: emptyAddressSet >,
    1.0e+7) .
)
