load consistency

mod ROLA-ANALYSIS is
  inc INITIAL-STATES .
  inc CONSISTENCY .

  --- Init parameters 
  eq nbOfRoTxns = 0 .  eq nbOfOpsPerRoTxn = 0 .
  eq nbOfWoTxns = 0 .  eq nbOfOpsPerWoTxn = 0 .
  eq nbOfRwTxns = 3 .  eq nbOfOpsPerRwTxn = 2 .  --- must be even number
  eq nbOfServs  = 2 .  eq nbOfKeys = 2 .  eq nbOfRepls = 1 .


  op initConfig : -> Config .
  eq initConfig = init(nbOfRoTxns,nbOfWoTxns,nbOfRwTxns,
      nbOfOpsPerRoTxn,nbOfOpsPerWoTxn,nbOfOpsPerRwTxn, 
      nbOfServs,nbOfKeys,nbOfRepls) . 

endm

---rew initConfig .
---search initConfig =>! C:Config .

---search [1] initConfig =>! < M:Address : Monitor | log: LOG:Log, AS:AttributeSet > C:Config 
  ---such that not rc(LOG:Log) .

---search [1] initConfig =>! < M:Address : Monitor | log: LOG:Log, AS:AttributeSet > C:Config 
  ---such that not ra(LOG:Log) .

---search [1] initConfig =>! < M:Address : Monitor | log: LOG:Log, AS:AttributeSet > C:Config 
  ---such that not cs(LOG:Log) .

---search [1] initConfig =>! < M:Address : Monitor | log: LOG:Log, AS:AttributeSet > C:Config 
  ---such that not ua(LOG:Log) .

---search [1] initConfig =>! < M:Address : Monitor | log: LOG:Log, AS:AttributeSet > C:Config 
  ---such that not si(LOG:Log) .

---search [1] initConfig =>! < M:Address : Monitor | log: LOG:Log, AS:AttributeSet > C:Config 
  ---such that not psi(LOG:Log) .

---search [1] initConfig =>! < M:Address : Monitor | log: LOG:Log, AS:AttributeSet > C:Config 
  ---such that not nmsi(LOG:Log) .

---search [1] initConfig =>! < M:Address : Monitor | log: LOG:Log, AS:AttributeSet > C:Config 
  ---such that not us(LOG:Log) .

search [1] initConfig =>! < M:Address : Monitor | log: LOG:Log, AS:AttributeSet > C:Config 
  such that not ser(LOG:Log) .

---search [1] initConfig =>! < M:Address : Monitor | log: LOG:Log, AS:AttributeSet > C:Config 
  ---such that not sser(LOG:Log) .

---(
rew dsg(
( 1 . 1 |-> < 1 |-> 0,1 |-> 2,true,< k1,< 0,0 > >,< k1,< 1,2 > > >, 
  1 . 2 |-> < 1 |-> 3,1 |-> 4,true,< k1,< 1,2 > >,< k1,< 1,4 > > >, 
  2 . 1 |-> < 2 |-> 1,2 |-> 5,true,< k1,< 1,4 > >,< k1,< 2,2 > > >)) .
)

---(
rew dsg-update(
(1 . 1 |-> < 1 |-> 0,1 |-> 2,false,(< k1,< 0,0 > >, < k2,< 0,0 > >),(< k1,< 1,2 > >, < k2,< 1,2 > >) >, 
1 . 2 |-> < 1 |-> 3,1 |-> 5,true,(< k1,< 2,2 > >, < k2,< 2,2 > >),(< k1,< 1,5 > >, < k2,< 1,5 > >) >,
2 . 1 |-> < 2 |-> 1,2 |-> 4,true,(< k1,< 0,0 > >, < k2,< 0,0 > >),(< k1,< 2,2 > >, < k2,< 2,2 > >) >)) .
)

---(
rew sser(
(1 . 1 |-> < 1 |-> 0,1 |-> 2,false,(< k1,< 0,0 > >, < k2,< 0,0 > >),(< k1,< 1,2 > >, < k2,< 1,2 > >) >, 
1 . 2 |-> < 1 |-> 3,1 |-> 5,true,(< k1,< 2,2 > >, < k2,< 2,2 > >),(< k1,< 1,5 > >, < k2,< 1,5 > >) >,
2 . 1 |-> < 2 |-> 1,2 |-> 4,true,(< k1,< 0,0 > >, < k2,< 0,0 > >),(< k1,< 2,2 > >, < k2,< 2,2 > >) >)) .
)

---q

